---
- name: Define btrfs subvolume options
  btrfssubvol_mount_options:
    - defaults
    - compress=zstd:3
    - relatime
    - discard=async
    - ssd

# Subvolumes will be owned by user root and group root.
# to specify owner and/or group, add:
# owner: name
# group: name
# to change permissions recursively, add: recurse: true

- name: Create btrfs subvolumes
  btrfssubvol_subvolumes:
    - name: home
      mount_point: /home
    - name: log
      mount_point: /var/log
    - name: tmp
      mount_point: /var/tmp
    - name: pkg
      mount_point: /var/cache/pacman/pkg
    - name: opt
      mount_point: /opt
    - name: media
      mount_point: /media
    - name: games
      mount_point: /games
      group: users
    - name: net
      mount_point: /net
