---
- name: Install mDNS packages
  become: true
  become_user: root
  community.general.pacman:
    name: "{{ item }}"
    state: present
  with_items:
    - avahi
    - nss-mdns

- name: Update nsswitch.conf
  become: true
  become_user: root
  ansible.builtin.lineinfile:
    path: /etc/nsswitch.conf
    state: present
    regexp: "^hosts: mymachines resolve .*"
    line: "hosts: mymachines mdns_minimal [NOTFOUND=return] resolve [!UNAVAIL=return] files myhostname dns"

- name: Enable Avahi mdns service
  become: true
  become_user: root
  ansible.builtin.service:
    name: avahi-daemon
    state: started
    enabled: true
