---
- name: Gather facts
  hosts: all
  tags:
    - always

- name: Core
  ansible.builtin.import_playbook: playbooks/core.yaml

- name: CLI
  ansible.builtin.import_playbook: playbooks/cli.yaml

# - name: Mail
#   ansible.builtin.import_playbook: playbooks/mail.yaml

# TODO: split into more playbooks
# - name: All
#   ansible.builtin.import_playbook: playbooks/all.yaml

# - name: Unorganized
#   ansible.builtin.import_playbook: playbooks/unorganized.yaml
