---
- name: Ensure directory exists
  become: true
  become_user: root
  ansible.builtin.file:
    path: /usr/local/share/kbd/keymaps
    state: directory
    mode: 0755

- name: Copy vconsole.conf
  become: true
  become_user: root
  ansible.builtin.template:
    src: vconsole.conf.j2
    dest: /etc/vconsole.conf
    mode: 0644
