---
- name: Install refind
  community.general.pacman:
    name:
      - refind
  register: refind_pacman

- name: Install refind to efi partition
  # We can't do this as a handler,
  # as the following tasks rely on files created in this step
  when: refind_pacman.changed  # noqa: no-handler
  changed_when: true
  ansible.builtin.command:
    cmd: refind-install

- name: Sanity check variables
  when:
    - LUKS.enabled
    - LUKS.cryptdevice_container
    - not LUKS.cryptdevice_uuid
  ansible.builtin.fail:
    msg: "LUKS.cryptdevice_container is set, while LUKS.cryptdevice_uuid is empty. Did you forget to set it in custom.yaml?"

- name: Template refind_linux.conf with LUKS
  ansible.builtin.template:
    src: LUKS.refind_linux.conf
    dest: /efi/refind_linux.conf
    mode: 0644
  when: LUKS.enabled

- name: Find UEFI partition
  ansible.builtin.shell: 'cat /etc/fstab |grep efi | grep UUID | cut -f 2'
  register: uefi_path

- name: Teach refind about Arch kernel version strings
  ansible.builtin.lineinfile:
    path: "{{ uefi_path.stdout | replace(' ', '') }}/EFI/refind/refind.conf"
    line: 'extra_kernel_version_strings linux-hardened,linux-rt-lts,linux-zen,linux-lts,linux-rt,linux'
    regexp: '^extra_kernel_version_strings '
    insertafter: '^#extra_kernel_version_strings'

- name: Get boot device UUID
  ansible.builtin.command: "blkid -s UUID -o value {{ root_device }}"
  register: refind_root_uuid

- name: Get swap device UUID
  ansible.builtin.shell: 'cat /etc/fstab | grep swap | grep UUID | cut -f 1'
  register: refind_swap_uuid

- name: Generate boot additional parameters
  ansible.builtin.set_fact:
    boot_additional_parameters: "{{ common_boot | join(' ') }}"

- name: Generate AMD boot additional parameters for AMD graphics
  ansible.builtin.set_fact:
    amd_additional_params: "{{ common_boot + amd_boot }}"
  when: system.graphics_card == "amd"
  register: combined_common_and_amd

- name: Combine AMD boot parameters
  ansible.builtin.set_fact:
    boot_additional_parameters: "{{ amd_additional_params | join(' ') }}"
  when: combined_common_and_amd

- name: Populate kernel command line root file
  ansible.builtin.template:
    src: refind_linux.conf.j2
    dest: /boot/refind_linux.conf
    mode: '0644'
  become: true
  when:
    - refind_root_uuid
    - refind_swap_uuid
    - not uki

- name: Create /etc/pacman.d/hooks/ directory
  ansible.builtin.file:
    path: /etc/pacman.d/hooks/
    state: directory
    mode: '0755'
  register: created_pacmand_hooks_dir

- name: Deploy refind hook
  ansible.builtin.copy:
    src: refind.hook
    dest: /etc/pacman.d/hooks/
    mode: '0644'
  when: created_pacmand_hooks_dir
