---
- name: Install required btrfs-progs package
  become: true
  become_user: root
  community.general.pacman:
    name:
      - btrfs-progs
    state: present

- name: Ensure directory exists
  ansible.builtin.file:
    path: /etc/mkinitcpio.conf.d
    state: directory
    mode: 0755
  loop:
    - /etc/mkinitcpio.conf.d
  become: true
  become_user: root

- name: Template drop-in files
  ansible.builtin.template:
    src: "{{ item }}"
    dest: /etc/mkinitcpio.conf.d/{{ item }}
    mode: 0644
  loop:
    - mkinitcpio.conf.j2
  notify: Regenerate initramfs
  become: true
  become_user: root
