---
- name: CLI
  hosts: all
  become: true
  become_user: "{{ user_name }}"
  roles:
    - { role: apprise, tags: ["apprise"] }
    - { role: bind, tags: ["bind"] }
    - { role: fish, tags: ["fish"] }
    - { role: fzf, tags: ["fzf"] }
    - { role: git, tags: ["git"] }
    - { role: gpg, tags: ["gpg"] }
    - { role: kubectl_stuff, tags: ["kubectl_stuff"] }
    - { role: ncdu, tags: ["ncdu"] }
    - { role: fastfetch, tags: ["fastfetch"] }
    - { role: nmap, tags: ["nmap"] }
    - { role: p7zip, tags: ["p7zip"] }
    - { role: ranger, tags: ["ranger"] }
    - { role: scripts, tags: ["scripts"] }
    - { role: tldr, tags: ["tldr"] }
    - { role: tmux, tags: ["tmux"] }
    - { role: wget, tags: ["wget"] }
  tags:
    - cli
