---
- name: Ensure directory exists
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: 0700
  loop:
    - ~/.ssh
    - ~/.ssh/ssh_config.d
    - ~/.ssh/sockets

- name: Copy ssh config
  ansible.builtin.copy:
    src: ssh_config
    dest: ~/.ssh/config
    mode: 0600

- name: Copy ssh conf files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: ~/.ssh/ssh_config.d/{{ item }}
    mode: 0600
  loop:
    - 01-ssh-devserver.conf
    - 02-ssh-homeserver.conf
    - 03-ssh-controlpersist.conf
    - 04-ssh-term.conf
